@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/post/comments/<postId>
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/commentsnames/66cc5d25ff80ab8a51451d40
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/66cc5d25ff80ab8a51451d40/66dc9b5a5a834aa0ec043a36
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "66d2cd28a49f5ff1b64f30df",
  "postId": "66cc5d25ff80ab8a51451d40",
  "comment": "this is comment 1",
  "profilePicture": "https://picsum.photos/200"
}
